name: markdown_editor
description: A Flutter app to edit and save markdown files

publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.17
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12
  file_picker: ^5.3.3
  expandable: ^5.0.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true